# Automated Testing Script for Incident-Simulation App
# Execute this in PowerShell: powershell -ExecutionPolicy Bypass -File test.ps1

$baseUrl = "http://localhost:3000"
$headers = @{ "Content-Type" = "application/json" }

function Show-Header ($title) {
    Write-Host "`n==================================================" -ForegroundColor Cyan
    Write-Host ">>> $title" -ForegroundColor Cyan
    Write-Host "==================================================" -ForegroundColor Cyan
}

# ---------------------------------------------------------
# Phase 1: Baseline Nominal Testing
# ---------------------------------------------------------
Show-Header "1. Fetching products (GET /products)"
$products = Invoke-RestMethod -Uri "$baseUrl/products" -Method Get
$products.products | Format-Table id, name, price, stock

Show-Header "2. Performing Admin Login (POST /login)"
$loginBody = @{ username = "admin"; password = "password123" } | ConvertTo-Json
$loginRes = Invoke-RestMethod -Uri "$baseUrl/login" -Method Post -Headers $headers -Body $loginBody
Write-Host "Login Success: $($loginRes.success)"
Write-Host "Token: $($loginRes.token)"

Show-Header "3. Adding Item to Cart (POST /cart)"
$cartBody = @{ productId = 1; quantity = 2 } | ConvertTo-Json
$cartRes = Invoke-RestMethod -Uri "$baseUrl/cart" -Method Post -Headers $headers -Body $cartBody
Write-Host "Cart Response: $($cartRes.message)"

Show-Header "4. Checking out Cart (POST /checkout)"
$checkoutRes = Invoke-RestMethod -Uri "$baseUrl/checkout" -Method Post -Headers $headers
Write-Host "Checkout Success: $($checkoutRes.success)"
Write-Host "Total Amount: $($checkoutRes.totalAmount)"

Show-Header "5. Processing Payment (POST /payment)"
$paymentBody = @{ amount = 1799.98; paymentMethod = "credit_card" } | ConvertTo-Json
$paymentRes = Invoke-RestMethod -Uri "$baseUrl/payment" -Method Post -Headers $headers -Body $paymentBody
Write-Host "Payment Status: $($paymentRes.status)"
Write-Host "Transaction ID: $($paymentRes.transactionId)"


# ---------------------------------------------------------
# Phase 2: Simulate Failure (payment_down)
# ---------------------------------------------------------
Show-Header "6. Simulating Failure: payment_down (POST /simulate-failure)"
$simBody = @{ type = "payment_down" } | ConvertTo-Json
$simRes = Invoke-RestMethod -Uri "$baseUrl/simulate-failure" -Method Post -Headers $headers -Body $simBody
Write-Host "Incident Simulated: $($simRes.activeIncident.type)"
Write-Host "Started At: $($simRes.activeIncident.startedAt)"

Show-Header "7. Attempting Payment during payment_down (POST /payment)"
try {
    Invoke-RestMethod -Uri "$baseUrl/payment" -Method Post -Headers $headers -Body $paymentBody
} catch {
    $errRes = $_.Exception.Response
    $statusCode = [int]$errRes.StatusCode
    $reader = New-Object System.IO.StreamReader($errRes.GetResponseStream())
    $body = $reader.ReadToEnd()
    Write-Host "Expected Failure - Status Code: $statusCode" -ForegroundColor Red
    Write-Host "Response Body: $body" -ForegroundColor Red
}

Show-Header "8. Querying Logs and Active Incident State (GET /api/logs)"
$logRes = Invoke-RestMethod -Uri "$baseUrl/api/logs" -Method Get
Write-Host "Active Incident In Logs: $($logRes.activeIncident.type)"
Write-Host "Last 5 Logs (Errors generated by simulation burst):"
$logRes.logs | Select-Object -First 5 | ForEach-Object {
    Write-Host "$($_.timestamp) [$($_.level)] - $($_.message)" -ForegroundColor Yellow
}


# ---------------------------------------------------------
# Phase 3: Resolve Incident
# ---------------------------------------------------------
Show-Header "9. Resolving Incident (POST /resolve-incident)"
$resolveRes = Invoke-RestMethod -Uri "$baseUrl/resolve-incident" -Method Post -Headers $headers
Write-Host "Resolution Message: $($resolveRes.message)"
Write-Host "Cleared Incident: $($resolveRes.incidentCleared.type)"

Show-Header "10. Retrying Payment after Resolution (POST /payment)"
$paymentBody2 = @{ amount = 100.00; paymentMethod = "credit_card" } | ConvertTo-Json
$paymentRes2 = Invoke-RestMethod -Uri "$baseUrl/payment" -Method Post -Headers $headers -Body $paymentBody2
Write-Host "Retried Payment Status: $($paymentRes2.status)"
Write-Host "New Transaction ID: $($paymentRes2.transactionId)"

Write-Host "`nTest Execution Complete!" -ForegroundColor Green
